### PR TITLE
Design facelift

### PR DESCRIPTION
**Pull request by aurri**
An attempt for better aesthetics and usability.

Demo: https://aurri.github.io/connector.land/

Feedback is welcome.

### CODE REVIEW

**Comment by ghost** [comment]
Looks so much better already.

**Comment by michielbdejong** [comment]
Awesome!
* There seems to be an empty line after line 9 or 10 of each table, maybe a css bug?
* In the near future, we'll probably want to display some simple graphs, something like http://michaelsmithnews.typepad.com/.a/6a0177444b0c2e970d017ee87a4c3c970d-pi - how can we do that? The graph would have to render based on a list of (x, y) points which are retrieved with xhr.

**Review by michielbdejong — CHANGES_REQUESTED** [review]
https://github.com/interledger/connector.land/pull/12#issuecomment-298637945

**Comment by aurri** [comment]
Nice, glad you liked it!

For the charts, I'd probably look into MetricsGraphics.js or Chart.js depending on the need.

The empty line was an intentional whitespace, but maybe it's better without it - fixed now.

Before:

before

After: 

after

**Review by michielbdejong — APPROVED** [review]

**Comment by justmoon** [comment]
@michielbdejong Go ahead and merge when you think this is ready!

**Pull request merged**
