### PR TITLE
Update hosts.js to add ilpkit-gce.fluid.money

### PR DESCRIPTION
**Pull request by sappenin**

### CODE REVIEW

**Comment by vhpoet** [comment]
@sappenin is it online? can't access right now.

**Comment by michielbdejong** [comment]
Thanks!

**Comment by vhpoet** [comment]
@sappenin ah, I think you just don't have an http -> https redirect. I was trying with http.

**Comment by sappenin** [comment]
@vhpoet Can you try again?  I have nginx setup to redirect port 80.  Seems to be working now on my end.

Also, on connector.land, it shows `no data` under the "Message Delay" column for my ILP-Kit.  Is something else misconfigured?

**Comment by vhpoet** [comment]
@sappenin still nope. It might be working for you because you already visited the https version. Browsers cache this. It would even work on incognito mode. Try with a different browser where you haven't opened ilpkit-gce.fluid.money yet.

**Comment by sappenin** [comment]
@vhpoet Nice catch!  Turns out my firewall in Google Cloud was blocking http traffic.  :(

Should be working now - wanna give it one more try?  (I'm getting a curl response via http, so I'm pretty sure it's working, but just in case).

**Comment by vhpoet** [comment]
@sappenin works 🎉

**Pull request merged**
